const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.bound,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Behaviors.LOS,
		C3.Behaviors.Sin,
		C3.Behaviors.Follow,
		C3.Plugins.Browser,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.shadowlight,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Arr,
		C3.Plugins.LocalStorage,
		C3.Plugins.gamepad,
		C3.Plugins.AJAX,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.shadowcaster,
		C3.Plugins.Tilemap,
		C3.Behaviors.Fade,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Particles,
		C3.Behaviors.Flash,
		C3.Behaviors.EightDir,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.EightDir.Acts.SetIgnoreInput,
		C3.Behaviors.EightDir.Acts.SetSpeed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.Audio.Acts.SetPaused,
		C3.JavaScriptInEvents.Egameplay_Event41_Act3,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.Bounce,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.InstanceSignal,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.OnInstanceSignal,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Exps.ColorValue,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.System.Exps.rgba,
		C3.Behaviors.Flash.Cnds.IsFlashing,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Behaviors.LOS.Cnds.HasLOSBetweenPositions,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Cnds.PickAll,
		C3.Behaviors.Follow.Acts.FollowObject,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Behaviors.MoveTo.Acts.Stop,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.EightDir.Acts.SetMaxSpeed,
		C3.Behaviors.EightDir.Cnds.CompareSpeed,
		C3.Behaviors.EightDir.Acts.Stop,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.gamepad.Cnds.IsButtonDown,
		C3.Plugins.gamepad.Cnds.CompareAxis,
		C3.Plugins.gamepad.Cnds.OnAnyButtonDown,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Cnds.AngleWithin,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.gamepad.Cnds.OnButtonDown,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Exps.projectversion,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Arr.Acts.SetX,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Behaviors.Tween.Cnds.OnAnyTweensFinished,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Arr.Cnds.ArrForEach,
		C3.Plugins.Arr.Exps.CurValue,
		C3.JavaScriptInEvents.Eportals_Event2_Act1,
		C3.JavaScriptInEvents.Eportals_Event4_Act1,
		C3.JavaScriptInEvents.Eportals_Event6_Act1,
		C3.JavaScriptInEvents.Eportals_Event8_Act1,
		C3.JavaScriptInEvents.Eportals_Event14_Act3
	];
};
self.C3_JsPropNameTable = [
	{HasKillAnimation: 0},
	{BoundToLayout: 0},
	{Bullet: 0},
	{EnemyA: 0},
	{Rotate: 0},
	{EnemyA_Saw: 0},
	{EnemyB: 0},
	{EnemyC: 0},
	{WaypointId: 0},
	{StartWaypointId: 0},
	{MaxWaypointId: 0},
	{MoveTo: 0},
	{EnemyD: 0},
	{StartDelay: 0},
	{HideDelay: 0},
	{RestartDelay: 0},
	{Length: 0},
	{Tween: 0},
	{Timer: 0},
	{EnemyE_Vertical: 0},
	{EnemyE_Horizontal: 0},
	{EnemyB2: 0},
	{EnemyB3_TrapDoor: 0},
	{ID: 0},
	{Waypoint: 0},
	{EnemyC2: 0},
	{ShootDelay: 0},
	{LineOfSight: 0},
	{EnemyG2_AutoTurret: 0},
	{EnemyTurret_Bullet: 0},
	{StartOffset: 0},
	{ClosedTime: 0},
	{ActiveTime: 0},
	{EnemyB4_TimedTrapDoor: 0},
	{NormalSpeed: 0},
	{FollowingSpeed: 0},
	{EnemyI_Follower: 0},
	{Sine: 0},
	{EnemyI_FollowerLight: 0},
	{Boss1: 0},
	{EnemyStun: 0},
	{Boss2: 0},
	{EnemyC2a: 0},
	{Boss3: 0},
	{Boss3_Spike1: 0},
	{Follow: 0},
	{EnemyJ_PathFollower: 0},
	{TurboPad: 0},
	{SpinnerSpikes: 0},
	{Boss4: 0},
	{Boss4Splat: 0},
	{Browser: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{Keyboard: 0},
	{LightMask512: 0},
	{ShadowLight: 0},
	{Sum: 0},
	{LightMaskTime: 0},
	{Audio: 0},
	{LightMask129: 0},
	{DebugText: 0},
	{DebugText2: 0},
	{UnlockedStars: 0},
	{LocalStorage: 0},
	{Gamepad: 0},
	{SummaryStarLight: 0},
	{AJAX: 0},
	{LevelColor: 0},
	{Touch: 0},
	{LevelsData: 0},
	{Tutorial1: 0},
	{Tutorial2: 0},
	{start: 0},
	{Tutorial4: 0},
	{Tutorial5: 0},
	{Tutorial3: 0},
	{Tutorial6: 0},
	{Tutorial7: 0},
	{g: 0},
	{g2: 0},
	{g3: 0},
	{g4: 0},
	{g5: 0},
	{g6: 0},
	{GroundStripes: 0},
	{TiledBackground: 0},
	{GroundDeco: 0},
	{Chimney: 0},
	{FanActive: 0},
	{FanBg: 0},
	{TiledBackground2: 0},
	{Panel: 0},
	{TiledBackground3: 0},
	{TiledBackground4: 0},
	{EnemyWallText: 0},
	{Solid: 0},
	{ShadowCaster: 0},
	{WallRound: 0},
	{Tilemap: 0},
	{WallRect: 0},
	{Deco: 0},
	{Star: 0},
	{Fade: 0},
	{PickupKeyA: 0},
	{DoorA: 0},
	{GroundEnemyBlocker: 0},
	{Window: 0},
	{OverBlock: 0},
	{OverBlock2: 0},
	{Active: 0},
	{SaveArea: 0},
	{LevelEnd: 0},
	{LoadingProgress: 0},
	{Cost: 0},
	{ShopAreaSpeed: 0},
	{ShopAreaSpeed_Progress: 0},
	{PickupKeyB: 0},
	{DoorB: 0},
	{WindowUnbrekable: 0},
	{LevelTimer: 0},
	{TeleportA: 0},
	{TeleportB: 0},
	{LevelNumber: 0},
	{PushX: 0},
	{PushY: 0},
	{ConveyorBelt: 0},
	{MenuText: 0},
	{IntroLevelEnd: 0},
	{Menu_LevelNo: 0},
	{Menu_LevelTime: 0},
	{SummaryPAR_Text: 0},
	{LevelNumber2: 0},
	{LevelsToUnlock: 0},
	{DoorLevelSelection: 0},
	{BigFloorText: 0},
	{HUD_PointsText: 0},
	{HUD_CoinsIcon: 0},
	{HUD_SaveTokens: 0},
	{HUD_Stars: 0},
	{HUD_Separator: 0},
	{HUD_TimeIcon: 0},
	{NotificationText: 0},
	{HUD_TimeBar: 0},
	{NotificationPanel: 0},
	{DragDrop: 0},
	{Joy: 0},
	{JoyBack: 0},
	{JoyLine: 0},
	{WindowParticles: 0},
	{KeyAParticles: 0},
	{KeyBParticles: 0},
	{DashCircle: 0},
	{KeyEffect: 0},
	{ShootParticles: 0},
	{BulletDestroyParticles: 0},
	{ChimneyParticles: 0},
	{SmokeParticles: 0},
	{Flash: 0},
	{StartCircle: 0},
	{BulletParticle: 0},
	{PlayerKilledParticles: 0},
	{LevelExitPoint: 0},
	{LevelId: 0},
	{LevelSelector: 0},
	{LevelStar1: 0},
	{LevelStar2: 0},
	{LevelStar3: 0},
	{logo: 0},
	{Menu_Continue: 0},
	{Menu_NewGame: 0},
	{Menu_Next: 0},
	{Menu_Retry: 0},
	{SummaryStar_Level: 0},
	{SummaryStar_PAR: 0},
	{SummaryStar_Star: 0},
	{IntroLevel: 0},
	{StickersLevel: 0},
	{Menu_LevelSelection: 0},
	{"8Direction": 0},
	{Player: 0},
	{PlayerSticker: 0},
	{BulletSoundEffect: 0},
	{PauseBg: 0},
	{DescriptionText: 0},
	{Pause_Resume: 0},
	{Pause_Sounds: 0},
	{Pause_Music: 0},
	{Pause_Exit: 0},
	{PauseMain: 0},
	{YouDiedOptionIcon: 0},
	{Pause_Joy: 0},
	{HUD_Pause: 0},
	{RequiredStars: 0},
	{GroundSticker: 0},
	{GroundStickerIcon: 0},
	{GamePausedText: 0},
	{YouDiedPanel: 0},
	{ContinuePanel2: 0},
	{PanelHeaderText: 0},
	{ReviveButton: 0},
	{RetryButton: 0},
	{Portal_Logo: 0},
	{Splash_BoltGoblin: 0},
	{Splash_CrazyGames: 0},
	{FadeOverlay: 0},
	{Enemies: 0},
	{RandomFrame: 0},
	{EnemyBlockers: 0},
	{HiddenPassages: 0},
	{Shops: 0},
	{Keys: 0},
	{Obstacles: 0},
	{MenuOptions: 0},
	{VirtualJoy: 0},
	{SummaryStars: 0},
	{PauseTexts: 0},
	{LevelStar: 0},
	{LevelTime: 0},
	{SelectedOption: 0},
	{DoorType: 0},
	{ShootDistance: 0},
	{DashCooldown: 0},
	{NormalMaxSpeed: 0},
	{SpeedMultiplier: 0},
	{JoystickSpeed_8Dir: 0},
	{JoystickSpeed_Free: 0},
	{NormalAcceleration: 0},
	{IsAlive: 0},
	{IsRevived: 0},
	{StickerId: 0},
	{DistanceAllowed: 0},
	{AngleTolerance: 0},
	{SoundsOn: 0},
	{MusicOn: 0},
	{VirtualJoyMode: 0},
	{CurrentLevel: 0},
	{IsPaused: 0},
	{UnlockedLevels: 0},
	{PauseSelectedOption: 0},
	{MusicVolume: 0},
	{SoundName: 0},
	{SoundVolume: 0},
	{MusicName: 0},
	{AllLevelStars: 0},
	{FadeTime: 0},
	{PAR: 0},
	{SumOfAllStars: 0},
	{MidgameVideoCounter: 0},
	{ActivePortal: 0}
];

self.InstanceType = {
	EnemyA: class extends self.ISpriteInstance {},
	EnemyA_Saw: class extends self.ISpriteInstance {},
	EnemyB: class extends self.ISpriteInstance {},
	EnemyC: class extends self.ISpriteInstance {},
	EnemyD: class extends self.ISpriteInstance {},
	EnemyE_Vertical: class extends self.ISpriteInstance {},
	EnemyE_Horizontal: class extends self.ISpriteInstance {},
	EnemyB2: class extends self.ISpriteInstance {},
	EnemyB3_TrapDoor: class extends self.ISpriteInstance {},
	Waypoint: class extends self.ISpriteInstance {},
	EnemyC2: class extends self.ISpriteInstance {},
	EnemyG2_AutoTurret: class extends self.ISpriteInstance {},
	EnemyTurret_Bullet: class extends self.ISpriteInstance {},
	EnemyB4_TimedTrapDoor: class extends self.ISpriteInstance {},
	EnemyI_Follower: class extends self.ISpriteInstance {},
	EnemyI_FollowerLight: class extends self.ISpriteInstance {},
	Boss1: class extends self.ISpriteInstance {},
	EnemyStun: class extends self.ISpriteInstance {},
	Boss2: class extends self.ISpriteInstance {},
	EnemyC2a: class extends self.ISpriteInstance {},
	Boss3: class extends self.ISpriteInstance {},
	Boss3_Spike1: class extends self.ISpriteInstance {},
	EnemyJ_PathFollower: class extends self.ISpriteInstance {},
	TurboPad: class extends self.ISpriteInstance {},
	SpinnerSpikes: class extends self.ISpriteInstance {},
	Boss4: class extends self.ISpriteInstance {},
	Boss4Splat: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Camera: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	LightMask512: class extends self.ISpriteInstance {},
	ShadowLight: class extends self.IShadowLightInstance {},
	Sum: class extends self.ISpriteInstance {},
	LightMaskTime: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	LightMask129: class extends self.ISpriteInstance {},
	DebugText: class extends self.ITextInstance {},
	DebugText2: class extends self.ITextInstance {},
	UnlockedStars: class extends self.IArrayInstance {},
	LocalStorage: class extends self.IInstance {},
	Gamepad: class extends self.IInstance {},
	SummaryStarLight: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	LevelColor: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	LevelsData: class extends self.IArrayInstance {},
	Tutorial1: class extends self.ISpriteInstance {},
	Tutorial2: class extends self.ISpriteInstance {},
	start: class extends self.ISpriteInstance {},
	Tutorial4: class extends self.ISpriteInstance {},
	Tutorial5: class extends self.ISpriteInstance {},
	Tutorial3: class extends self.ISpriteInstance {},
	Tutorial6: class extends self.ISpriteInstance {},
	Tutorial7: class extends self.ISpriteInstance {},
	g: class extends self.ISpriteInstance {},
	g2: class extends self.ISpriteInstance {},
	g3: class extends self.ISpriteInstance {},
	g4: class extends self.ISpriteInstance {},
	g5: class extends self.ISpriteInstance {},
	g6: class extends self.ISpriteInstance {},
	GroundStripes: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	GroundDeco: class extends self.ISpriteInstance {},
	Chimney: class extends self.ISpriteInstance {},
	FanActive: class extends self.ISpriteInstance {},
	FanBg: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Panel: class extends self.ITiledBackgroundInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	EnemyWallText: class extends self.ITextInstance {},
	WallRound: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	WallRect: class extends self.ISpriteInstance {},
	Deco: class extends self.ISpriteInstance {},
	Star: class extends self.ISpriteInstance {},
	PickupKeyA: class extends self.ISpriteInstance {},
	DoorA: class extends self.ISpriteInstance {},
	GroundEnemyBlocker: class extends self.ISpriteInstance {},
	Window: class extends self.ISpriteInstance {},
	OverBlock: class extends self.ISpriteInstance {},
	OverBlock2: class extends self.ISpriteInstance {},
	SaveArea: class extends self.ISpriteInstance {},
	LevelEnd: class extends self.ISpriteInstance {},
	ShopAreaSpeed: class extends self.ISpriteInstance {},
	ShopAreaSpeed_Progress: class extends self.ISpriteInstance {},
	PickupKeyB: class extends self.ISpriteInstance {},
	DoorB: class extends self.ISpriteInstance {},
	WindowUnbrekable: class extends self.ISpriteInstance {},
	LevelTimer: class extends self.ITextInstance {},
	TeleportA: class extends self.ISpriteInstance {},
	TeleportB: class extends self.ISpriteInstance {},
	LevelNumber: class extends self.ITextInstance {},
	ConveyorBelt: class extends self.ISpriteInstance {},
	MenuText: class extends self.ITextInstance {},
	IntroLevelEnd: class extends self.ISpriteInstance {},
	Menu_LevelNo: class extends self.ITextInstance {},
	Menu_LevelTime: class extends self.ITextInstance {},
	SummaryPAR_Text: class extends self.ITextInstance {},
	LevelNumber2: class extends self.ITextInstance {},
	DoorLevelSelection: class extends self.ISpriteInstance {},
	BigFloorText: class extends self.ITextInstance {},
	HUD_PointsText: class extends self.ITextInstance {},
	HUD_CoinsIcon: class extends self.ISpriteInstance {},
	HUD_SaveTokens: class extends self.ITiledBackgroundInstance {},
	HUD_Stars: class extends self.ITiledBackgroundInstance {},
	HUD_Separator: class extends self.ISpriteInstance {},
	HUD_TimeIcon: class extends self.ISpriteInstance {},
	NotificationText: class extends self.ITextInstance {},
	HUD_TimeBar: class extends self.ITiledBackgroundInstance {},
	NotificationPanel: class extends self.ISpriteInstance {},
	Joy: class extends self.ISpriteInstance {},
	JoyBack: class extends self.ISpriteInstance {},
	JoyLine: class extends self.ISpriteInstance {},
	WindowParticles: class extends self.IParticlesInstance {},
	KeyAParticles: class extends self.IParticlesInstance {},
	KeyBParticles: class extends self.IParticlesInstance {},
	DashCircle: class extends self.ISpriteInstance {},
	KeyEffect: class extends self.ISpriteInstance {},
	ShootParticles: class extends self.IParticlesInstance {},
	BulletDestroyParticles: class extends self.IParticlesInstance {},
	ChimneyParticles: class extends self.IParticlesInstance {},
	SmokeParticles: class extends self.IParticlesInstance {},
	StartCircle: class extends self.ISpriteInstance {},
	BulletParticle: class extends self.ISpriteInstance {},
	PlayerKilledParticles: class extends self.IParticlesInstance {},
	LevelExitPoint: class extends self.ISpriteInstance {},
	LevelSelector: class extends self.ISpriteInstance {},
	LevelStar1: class extends self.ISpriteInstance {},
	LevelStar2: class extends self.ISpriteInstance {},
	LevelStar3: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	Menu_Continue: class extends self.ISpriteInstance {},
	Menu_NewGame: class extends self.ISpriteInstance {},
	Menu_Next: class extends self.ISpriteInstance {},
	Menu_Retry: class extends self.ISpriteInstance {},
	SummaryStar_Level: class extends self.ISpriteInstance {},
	SummaryStar_PAR: class extends self.ISpriteInstance {},
	SummaryStar_Star: class extends self.ISpriteInstance {},
	IntroLevel: class extends self.ISpriteInstance {},
	StickersLevel: class extends self.ISpriteInstance {},
	Menu_LevelSelection: class extends self.ISpriteInstance {},
	Player: class extends self.ISpriteInstance {},
	PlayerSticker: class extends self.ISpriteInstance {},
	BulletSoundEffect: class extends self.ISpriteInstance {},
	PauseBg: class extends self.ITiledBackgroundInstance {},
	DescriptionText: class extends self.ITextInstance {},
	Pause_Resume: class extends self.ITextInstance {},
	Pause_Sounds: class extends self.ITextInstance {},
	Pause_Music: class extends self.ITextInstance {},
	Pause_Exit: class extends self.ITextInstance {},
	PauseMain: class extends self.ITiledBackgroundInstance {},
	YouDiedOptionIcon: class extends self.ISpriteInstance {},
	Pause_Joy: class extends self.ITextInstance {},
	HUD_Pause: class extends self.ISpriteInstance {},
	GroundSticker: class extends self.ISpriteInstance {},
	GroundStickerIcon: class extends self.ISpriteInstance {},
	GamePausedText: class extends self.ITextInstance {},
	YouDiedPanel: class extends self.ITiledBackgroundInstance {},
	ContinuePanel2: class extends self.ITiledBackgroundInstance {},
	PanelHeaderText: class extends self.ITextInstance {},
	ReviveButton: class extends self.ITextInstance {},
	RetryButton: class extends self.ITextInstance {},
	Portal_Logo: class extends self.ISpriteInstance {},
	Splash_BoltGoblin: class extends self.ISpriteInstance {},
	Splash_CrazyGames: class extends self.ISpriteInstance {},
	FadeOverlay: class extends self.ISpriteInstance {},
	Enemies: class extends self.ISpriteInstance {},
	RandomFrame: class extends self.ISpriteInstance {},
	EnemyBlockers: class extends self.ISpriteInstance {},
	HiddenPassages: class extends self.ISpriteInstance {},
	Shops: class extends self.ISpriteInstance {},
	Keys: class extends self.ISpriteInstance {},
	Obstacles: class extends self.ISpriteInstance {},
	MenuOptions: class extends self.ISpriteInstance {},
	VirtualJoy: class extends self.ISpriteInstance {},
	SummaryStars: class extends self.ISpriteInstance {},
	PauseTexts: class extends self.ITextInstance {}
}